[package]
name = "nxzr_core"
version.workspace = true
description = "The NXZR project: the core module"
readme = "README.md"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition = "2021"
publish = false

[dependencies]
lazy_static = "1.4.0"
once_cell = "1.17.0"
strum = { version = "0.24.1", features = ["derive"] }
strum_macros = "0.24"
