[package]
name = "nxzr_core"
version.workspace = true
description = "The NXZR project: the core module"
readme = "README.md"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition = "2021"
publish = false

[dependencies]
