[workspace]
members = [
    "nxzr_core",
    "nxzr_device",
    "nxzr_proto",
    "nxzr_server",
    "nxzr_gui/src-tauri",
]

[workspace.package]
version = "0.1.0"
authors = ["Preco Plusb <plusb21@gmail.com>"]
repository = "https://github.com/preco21/nxzr"
license = "UNLICENSED"
