[package]
name = "nxzr_install"
version.workspace = true
description = "NXZR project: the installer modules"
readme = "README.md"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition = "2021"
publish = false

[dependencies]
