[package]
name = "nxzr_server"
version.workspace = true
description = "NXZR project: server demon application"
readme = "README.md"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition = "2021"
publish = false

[dependencies]
log = "0.4.17"
env_logger = "0.9.1"
tokio = "1.21.2"
# bluer = { version = "0.15.1", features = ["full"] }
nxzr_core = { path = "../nxzr_core" }
