[package]
name = "nxzr_server"
version = "0.1.0"
authors = ["Plusb Preco <plusb21@gmail.com>"]
description = "The NXZR project: the server application"
repository = "https://github.com/preco21/nxzr"
readme = "readme.md"
license = "UNLICENSED"
edition = "2021"
publish = false

[dependencies]
log = "0.4.17"
env_logger = "0.9.1"
tokio = { version = "1.21.2", features = ["full"] }
bluer = { version = "0.15.1", features = ["full"] }
