[package]
name = "nxzr_gui"
version.workspace = true
description = "The NXZR project: the gui application"
readme = "README.md"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition = "2021"
publish = false

[dependencies]
