[package]
name = "nxzr_gui"
version.workspace = true
description = "NXZR project: gui application"
readme = "README.md"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition = "2021"
publish = false

[dependencies]
