[package]
name = "nxzr_transport"
version.workspace = true
description = "NXZR project: transport module"
readme = "README.md"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition = "2021"
publish = false

[dependencies]
libc = "0.2.140"
tokio = { version = "1.25.0", features = ["sync", "net", "io-util"] }

[dev-dependencies]
tokio = { version = "1.25.0", features = [
    "sync",
    "io-std",
    "io-util",
    "rt-multi-thread",
] }
